sudo: required
services:
        - docker
before_install:
        - cd data/ds2 && sh build-image.sh && sh run-image.sh && ./check-health.sh && cd ../../

language: python
python:
        - "3.6"
install:
        - pip install -r requirements.txt
        - pip install -r requirements_test.txt
script:
        - coverage run --source=eddytools setup.py test
after_success:
        - coveralls
